### PR TITLE
Fix broken types in index.d.ts

### LINKED ISSUE #103: Cannot import OGCGeometry enum
When you import OGCGeometry it fails with this error
```
Error: export
 'OGCGeometry' (imported as 'OGCGeometry') was not found in '@mapbox/shp-write' (possible exports: download,
 write, zip)
```

### LINKED ISSUE #104: Type errors due to default values in type file
There are a few types that supply a default value, which is not allowed in types.
They are:
```
    options?: DownloadOptions & ZipOptions = {}
    options: DownloadOptions & ZipOptions = {},
    stream = false
```
They throw this error
 TS2371: A parameter initializer is only allowed in a function or constructor implementation.

### PR DESCRIPTION
**Pull request by rooby**
- Fixing the enum: In this case the enum is not really an enum is is a set of strings that map to the properties of a JS object. - Fixes #103 
- Removing the default values. - Fixes #104

### CODE REVIEW

File: dist/index.d.ts [hunk 1]
```diff
@@ -69,6 +68,6 @@ declare module "@mapbox/shp-write" {
 
   export function zip<T extends OutputType>(
     geojson: GeoJSON.FeatureCollection,
-    options: DownloadOptions & ZipOptions = {},
-    stream = false): Promise<OutputByType[T]>;
+    options: DownloadOptions & ZipOptions,
```
Comment (sheindel) [inline dist/index.d.ts:71]: This looks good, but this argument and `stream` should theoretically be optional in both methods, so can you change that too while you're at it? Thanks!

**Review by sheindel — CHANGES_REQUESTED** [review]
Looks good but `options` and `stream` args in `zip` both need marked as optional as well

**Comment by rooby** [comment]
Thanks for the quick review @sheindel .
I have made those parameters optional now.

**Comment by sheindel** [comment]
Thanks for doing this! I'll try to get mapbox to put out a release tomorrow

**Comment by rooby** [comment]
No problem. Thanks
